### ISSUE TITLE
ValidationError but appears correct

### ISSUE THREAD

**Issue by andyoneal** [MeltanoLabs/target-postgres#167]
Getting this validation error when running combined with tap-hubspot (potloc variant). It seems like this is an array?

I'm a bit out of my depth here on correct json schemas and being able to tell if this is a tap or target issue. Might be my own misunderstanding.

```
jsonschema.exceptions.ValidationError: '[{"category": "HUBSPOT_DEFINED", "typeId": 2, "label": "Primary Company"}, {"category": "HUBSPOT_DEFINED", "typeId": 280, "label": null}]' is not of type 'array'
Failed validating 'type' in schema['properties']['associationTypes']:
    {'items': {'properties': {'category': {'type': ['null', 'string']},
                              'label': {'type': ['null', 'string']},
                              'typeId': {'type': ['null', 'integer']}},
               'type': 'object'},
     'type': 'array'}
```

**Comment by edgarrmondragon** [comment]
I think this

```
'[{"category": "HUBSPOT_DEFINED", "typeId": 2, "label": "Primary Company"}, {"category": "HUBSPOT_DEFINED", "typeId": 280, "label": null}]'
```

is actually a JSON array _string_ so that's probably why validation is failing.

The tap's probably emitting the record with `associationTypes` as a string, rather than an array.

**Comment by andyoneal** [comment]
You're right. Looks like it's [defaulting to string.](https://github.com/potloc/tap-hubspot/blob/b6713cf0bd619e8736215d119d851697ee58c4f0/tap_hubspot/client.py#L103)

Will check with the tap then.

**Comment by andyoneal** [comment]
Turns out this is likely an SDK issue https://github.com/meltano/sdk/issues/1204
