### ISSUE TITLE
Bug in Upsert logic

### ISSUE THREAD

**Issue by rkjk** [MeltanoLabs/target-postgres#169]
The current logic for upsert of records is incorrect. I tried to send a PR but am unable to create a branch as it appears I may not have push access in this repo. In any case I will paste the incorrect code snippet here and the correct version.

In `sinks.py`, this snippet in the `upsert` function performs the update:
https://github.com/MeltanoLabs/target-postgres/blob/0c82a7f50b8b930b6624a80b04753e8e9105dd79/target_postgres/sinks.py#L229-L235

This looks for duplicates between the target and temp tables, and then performs the upsert on the temp table. Since the temp table is dropped after the operation completes, the updates are lost. The Updates should be performed on the target table.

```
           for column_name in self.schema["properties"].keys():
                from_table_column: sqlalchemy.Column = from_table.columns[column_name]
                to_table_column: sqlalchemy.Column = to_table.columns[column_name]
                update_columns[to_table_column] = from_table_column.                        # Change here

            update_stmt = (
                update(to_table).where(where_condition).values(update_columns)          # Change here
            )
```
Apologies for the clunky presentation.

**Comment by andyoneal** [comment]
Just want to confirm this is an issue. Looking at the results in the `test_users` table created by test_relational_data, the upsert obviously did not update existing records. For example, the row with `id=1` has `name=Yannis` but should be `name=Johny`.

**Comment by visch** [comment]
@rkjk  This is fixed, sorry it took this long major bug caused by me. Thanks @andyoneal  for fixing this
