### ISSUE TITLE
The target is not installing because of the new Poetry Core release (v1.7.0)

### ISSUE THREAD

**Issue by derbysh** [MeltanoLabs/target-postgres#179]
The new Poetry version has some breaking changes, so there is now a dependency resolution error when you try to install the target.
I had to restrict version manually as `<1.7.0` in `pyproject.toml` to make it work.
![image](https://github.com/MeltanoLabs/target-postgres/assets/95277135/811fc3b2-fac3-4a58-921c-7cd9c7941218)

**Comment by edgarrmondragon** [comment]
Hi @derbysh!

I can install directly from git using

```
pipx install git+https://github.com/MeltanoLabs/target-postgres.git
```

so perhaps you caught a bug before [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) [`v1.0.1`](https://github.com/mtkennerly/poetry-dynamic-versioning/releases/tag/v1.0.1) was published?
