### ISSUE TITLE
bug: `number` singer type is mapping to `serial 4` in postgres

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/target-postgres#193]
I'm seeing what looks like it might be a bug (I'm on the latest release) where I get the same error message as https://github.com/MeltanoLabs/target-postgres/issues/26 `sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range`.

The difference is that the column being created in the table is `serial 4` for the `id` column from the singer messages below, where the value is 34639314995. The singer data type is number.

[THIS IS TEST DATA]
```
{"type": "SCHEMA", "stream": "locations", "schema": {"properties": {"active": {"type": "boolean"}, "address1": {"type": ["string", "null"]}, "address2": {"type": ["string", "null"]}, "city": {"type": ["string", "null"]}, "country": {"type": ["string", "null"]}, "country_code": {"type": ["string", "null"]}, "created_at": {"type": ["string", "null"]}, "id": {"type": "number"}, "legacy": {"type": "boolean"}, "name": {"type": ["string", "null"]}, "phone": {"type": ["string", "null"]}, "province": {"type": ["string", "null"]}, "province_code": {"type": ["string", "null"]}, "updated_at": {"type": ["string", "null"]}, "zip": {"type": ["string", "null"]}, "localized_country_name": {"type": ["string", "null"]}, "localized_province_name": {"type": ["string", "null"]}}, "type": "object"}, "key_properties": ["id"]}
{"type": "RECORD", "stream": "locations", "record": {"id": 34639314995, "name": "111 Main St", "address1": "111 Main St", "address2": null, "city": "Sterling Heights", "zip": "48312", "province": "Michigan", "country": "US", "phone": "", "created_at": "2019-11-05T21:31:25-05:00", "updated_at": "2019-11-05T21:31:29-05:00", "country_code": "US", "province_code": "MI", "legacy": false, "active": true, "localized_country_name": "United States", "localized_province_name": "Michigan"}, "time_extracted": "2023-09-15T19:33:01.841018+00:00"}
```

cc @visch

**Comment by visch** [comment]
Curious, I'd expect the number to get created as a numeric and that number to fit in there fine. 

It's odd it says integer out of range, that must be coming from something bigger than a serial 4 as it's bigger than the maximum here  2^31 https://www.postgresql.org/docs/current/datatype-numeric.html but I don't think that matters here as the data should just go into the target hmmmm

**Comment by sebastianswms** [comment]
I dove in and tracked down the source of this. Although target-postgres was correctly identifying the data as a numeric, when sqlalchemy went to insert the `id` column it would change it to be a serial4. Why? It's because sqlalchemy defaults to having primary key columns be auto-increment, and numeric columns can't handle that. The fix was to explicitly disable auto-incrementing when specifying column types. That way, sqlalchemy doesn't turn numeric into serial and the problem is solved.
