### ISSUE TITLE
meltanolabs-target-postgres v0.0.8 and meltano v3 are conflicting

### ISSUE THREAD

**Issue by silverbullet1** [MeltanoLabs/target-postgres#196]
```
13:07:35  The conflict is caused by:
13:07:35      meltano[psycopg2] 3.0.0 depends on sqlalchemy<3.0.0 and >=2.0.19
13:07:35      meltanolabs-target-postgres 0.0.8 depends on sqlalchemy<2
13:07:35  
13:07:35  To fix this you could try to:
13:07:35  1. loosen the range of package versions you've specified
13:07:35  2. remove package versions to allow pip attempt to solve the dependency conflict
13:07:35  
```

I am trying to setup a docker container with meltano and target-postgres. Should I be using pipx inside docker ?

**Comment by edgarrmondragon** [comment]
@silverbullet1 I think you're probably trying to install Meltano and this tap in the same virtual environment. That's not normally expected to work. Running `meltano install` if your project is in the container should work.

Can you confirm?

**Comment by silverbullet1** [comment]
Yes, thanks. I was trying to install them as a part of requirements.txt
