### ISSUE TITLE
prepare_table does SDK handle this? If so migrate to it

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#256]
@visch @sebastianswms this is great!

One thought when I saw this though was that I worked on similar improvements in the SDK (re: https://github.com/meltano/sdk/pull/1779), not sure if its exactly the same or not. Maybe you've already done this recently but you might want to compare what youre doing in the overridden methods here to make sure its not already done in the SDK for you. Its been a while since this target was created and the SDK has come a long way. Overridden methods wont get to take advantage of ongoing improvements so removing them if theyre no longer needed could be a beneficial.

_Originally posted by @pnadolny13 in https://github.com/MeltanoLabs/target-postgres/issues/228#issuecomment-1836236297_

**Comment by sebastianswms** [comment]
I gave it a couple hours and wasn't able to get a reasonable implementation with the SDK's new prepare_table(). Many of the methods in target-postgres are overridden and have different expectations for input parameters than what is found in the SDK, meaning that it would take a lot to "unwind" the current target-postgres implementation (not as simple as just removing the prepare_table() override).

Based just on comparing the two codebases visually, I expect that the SDK does not address the same problems as #228. Following the path of execution, it's still O([number of columns]) db queries to prepare a table. Caching would speed things up after the initial run, but it would still fundamentally requires a large number of queries to set up.

**Comment by visch** [comment]
Thanks for looking!
