### ISSUE TITLE
Support for empty key properties

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#54]
Currently we do not support empty key properties in this target. To do this we'd need to update our strategies to do an "append only" type of add when there's no key properties set.

**Comment by menzenski** [comment]
Has there been any progress made on this? We're new adopters of this target and haven't run into this issue yet, but I expect that we will. I'm happy to try to contribute this but would likely need some direction.

**Comment by visch** [comment]
@menzenski  Solved with https://github.com/MeltanoLabs/target-postgres/pull/138

**Comment by menzenski** [comment]
@visch awesome, thank you!
