### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#71]
This is technically already supported via the sqlalchemy_url configuration. But we should add config option(s) for SSL as well so you don't have to use `sqlalchemy_url` to support this. 

Also as a part of this we should note in the `sqlalchemy_url` and `dialect+driver` that these settings are not safe to use as they can change significantly in the future, they should be used in combination with creating a ticket going over why you had to use the `sqlalchemy_url` and could not make the original configuration settings work.

**Comment by aaronsteers** [comment]
Related:

- https://github.com/dataops-tk/tapdance/pull/43
- https://towardsdatascience.com/how-to-connect-to-a-postgresql-database-with-python-using-ssh-tunnelling-d803282f71e7#e325
- Implementation in `tap-mysql`: https://github.com/transferwise/pipelinewise-tap-mysql/commit/2f1b0fd4c69a440350c2a92ad2fef8bd417c080e
