### ISSUE TITLE
Support for activate version

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#72]

**Comment by aaronsteers** [comment]
Related PR:

- https://github.com/meltano/sdk/pull/985

In theory, this was mostly complete, but I never had time to run manual or automated tests.

**Comment by aaronsteers** [comment]
@visch and @edgarrmondragon - Pardon my errant comment above. That WIP PR is for the tap-side implementation.

Those challenges around _sending_ `ACTIVATE_VERSION` message and the enabling `version` integer property are unrelated to the needs here on the target.

For target-side implementation, I think we want ideally a 'deletion' but with two possible implementations:

1. Only if something like `hard_delete=True` in `config`, then fully delete rows that have expired when an `ACTIVATE_VERSION` message is received.
2. In all other cases, if `ACTIVATE_VERSION` is received, then update records deleted records and set the [`_sdc_deleted_at` metadata column](https://sdk.meltano.com/en/latest/implementation/record_metadata.html) in the target table to the current timestamp.

If the above is correct, and if soft delete behavior is the right "safe default", we can chose to _only_ implement the second behavior in this first pass, and the 'hard delete' behavior could be added as a later addition.

**Comment by visch** [comment]
@aaronsteers  Just rubberduckied this and I think I understand ignore this for a second I"ll get it updated. I think the implementation may be correct actually!

**Comment by aaronsteers** [comment]
Thanks, @visch. My understanding is that records should come through with a `_sdc_table_version` property, but I could be mistaken on that front.

https://sdk.meltano.com/en/latest/implementation/record_metadata.html

And it's nice to see that a lot of the code may already be written. What might be useful is a manual test to see how it performs. Some of that code may have been written optimistically and not ever actually tested with a proper manual or unit test. 🙃

**Comment by visch** [comment]
> 



> Thanks, @visch. My understanding is that records should come through from the source with a `_sdc_table_version` property or similar, but I could be mistaken on that front.
> 
> https://sdk.meltano.com/en/latest/implementation/record_metadata.html
> 
> And it's nice to see that a lot of the code may already be written. What might be useful is a manual test to see how it performs. Some of that code may have been written optimistically and not ever actually tested with a proper manual or unit test. 🙃

Yeah I thought that too, just updated the comment above to be as accurate as I know right now.  It looks like `_sdc_table_version` isn't in the `record`  object of a `RECORD` message right now for `transferwise` variants. So we may want to implement the "correct" spec and then maybe allow for the transferwise style to work too? I'm not sure

**Comment by aaronsteers** [comment]
> It looks like _sdc_table_version isn't in the record object of a RECORD message right now for transferwise variants.

Is it perhaps in a `version` field which is top-level of the `RECORD` message?

**Comment by edgarrmondragon** [comment]
@aaronsteers @visch I think we should follow the pipelinewise version of the version extension and put it at the top-level of the `RECORD` message, with optional support for the `_sdc_table_version` record-level field, and a clear deprecation timeline in case someone's already relying on this (probably nobody, really).

**Comment by visch** [comment]
@edgarrmondragon  and @aaronsteers  thank you both! 

It looks like the SDK does have support for this baked in via the metadata columns ( if  `add_record_metadata` is set via Config)  . So if metadata columns are enabled activate_version messages kind of work). I'm writing some tests now and tweaking the activate version function slightly to work with the use cases I've hit in my testing / tweaking. 

Next open question I have is if `add_record_metadata` should be our flag to turning on/off activate version messages? And do we want a `config` value to turn on and off activate version messages. 

I'll implement the way that's easiest right now with the way the SDK is built and put it in the PR for you all to see and we can tweak it.

**Comment by aaronsteers** [comment]
@visch - Because record metadata is required for some critical operations, I'd be fine with enabling by default for our default implementation. Developers should be able to redefine the setting in order to use a different default.

Another developer-side customization lever would be to drive our behavior based on the presence of a `capabilities` array including `activate-version` or `soft-delete`/`hard-delete`. Lots of options here and we could make it an office hours or bespoke zoom topic if helpful.

**Comment by visch** [comment]
@aaronsteers  / @edgarrmondragon  https://github.com/MeltanoLabs/target-postgres/pull/89/files works, I have 2 more tests I thought about that seem pretty scary that I want to implement. But if you all want to take a look now that would be helpful!

**Comment by visch** [comment]
> @aaronsteers / @edgarrmondragon https://github.com/MeltanoLabs/target-postgres/pull/89/files works, I have 2 more tests I thought about that seem pretty scary that I want to implement. But if you all want to take a look now that would be helpful!

@aaronsteers  Yes what I worried about is true we do have an issue with activate_version. I'm going to have to do some spec writing here to get this cleared up and diving.

**Comment by TyShkan** [comment]
What is the current state of ACTIVATE_VERSION message type for taps/targets? What kind of issues are still unresolved?

**Comment by edgarrmondragon** [comment]
@TyShkan in the singer SDK it's waiting to be implemented on both ends: taps don't currently emit the message, and targets in general don't process it.

**Comment by TyShkan** [comment]
@edgarrmondragon is there any issues left on the SDK side?

We've had a conversation with @visch in [Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1697883895758499) and I'm trying to understand if there is a blocker and where it is.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon is there any issues left on the SDK side?
> 
> We've had a conversation with @visch in [Slack](https://meltano.slack.com/archives/C01TCRBBJD7/p1697883895758499) and I'm trying to understand if there is a blocker and where it is.

@TyShkan No real blockers. The relevant issue is https://github.com/meltano/sdk/issues/18 and https://github.com/meltano/sdk/pull/985 is a PR that went stale.
