### ISSUE TITLE
SQLAlchemy 2.0 Deprecation warnings

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/target-postgres#87]
1. ```  /home/visch/git/target-postgres/target_postgres/connector.py:70: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9) ```

2.   /home/visch/git/target-postgres/.venv/lib/python3.8/site-packages/singer_sdk/connectors/sql.py:638: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0".

3.  /home/visch/git/target-postgres/target_postgres/sinks.py:287: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0.

**Comment by edgarrmondragon** [comment]
This target uses SQLAlchemy 2!
